"""empty message

Revision ID: 06740c57bc83
Revises: 
Create Date: 2026-02-02 14:34:45.474408

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '06740c57bc83'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('characters',
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('character_type', sa.String(), nullable=False),
    sa.Column('abilities', sa.String(), nullable=False),
    sa.Column('inventory', sa.JSON(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('uuid'),
    sa.UniqueConstraint('uuid')
    )
    op.create_table('maps',
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('location_name', sa.String(length=130), nullable=False),
    sa.Column('coordinates', sa.JSON(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('quests_available', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('uuid'),
    sa.UniqueConstraint('location_name')
    )
    op.create_table('players',
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('health', sa.Integer(), nullable=True),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('inventory', sa.JSON(), nullable=True),
    sa.Column('current_quest', sa.JSON(), nullable=True),
    sa.Column('current_location_id', sa.Integer(), nullable=True),
    sa.Column('character_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['character_id'], ['characters.uuid'], ),
    sa.ForeignKeyConstraint(['current_location_id'], ['maps.uuid'], ),
    sa.PrimaryKeyConstraint('uuid'),
    sa.UniqueConstraint('uuid')
    )
    op.create_table('quests',
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('outcomes', sa.JSON(), nullable=False),
    sa.Column('is_completed', sa.Boolean(), nullable=True),
    sa.Column('location_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['location_id'], ['maps.uuid'], ),
    sa.PrimaryKeyConstraint('uuid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('quests')
    op.drop_table('players')
    op.drop_table('maps')
    op.drop_table('characters')
    # ### end Alembic commands ###
